# Solve 30 exercises from 100

In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np


In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)
import numpy as np

print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
print(np.show_config())


NumPy version: 1.24.3

NumPy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

In [3]:
#### 3. Create a null vector of size 10 (★☆☆)
import numpy as np

null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#### 4. How to find the memory size of any array (★☆☆)
import numpy as np

# Create a sample array
arr = np.zeros((4, 4))  

# Calculate memory size in bytes
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 128 bytes


In [7]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
import numpy as np; help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [8]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1  # Set the fifth value 
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
import numpy as np

vector_10_to_49 = np.arange(10, 50)
print(vector_10_to_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
import numpy as np

original_vector = np.array([1, 2, 3, 4, 5])  # Example vector (replace with your vector)
reversed_vector = original_vector[::-1]

print("Original vector:", original_vector)
print("Reversed vector:", reversed_vector)


Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


In [15]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
import numpy as np

matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)

print("Indices of non-zero elements:", nonzero_indices)


Indices of non-zero elements: (array([0, 1, 4], dtype=int64),)


In [17]:
#### 11. Create a 3x3 identity matrix (★☆☆)
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
import numpy as np

random_array_3x3x3 = np.random.rand(3, 3, 3)
print(random_array_3x3x3)


[[[0.41504511 0.07971764 0.77895431]
  [0.92088936 0.16669365 0.45217773]
  [0.35796274 0.78043131 0.01596194]]

 [[0.67984964 0.73288702 0.5884693 ]
  [0.1369469  0.74051647 0.94266106]
  [0.20173983 0.52293702 0.84327247]]

 [[0.98648293 0.96287605 0.85731975]
  [0.84661548 0.68347097 0.67064581]
  [0.17050217 0.16067235 0.06344879]]]


In [19]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
import numpy as np

# Create a 10x10 array with random values
random_array_10x10 = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_value = np.min(random_array_10x10)
max_value = np.max(random_array_10x10)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.020747044362116385
Maximum value: 0.993172432334869


In [20]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
import numpy as np

# Create a random vector of size 30
random_vector = np.random.randn(30)

# Calculate the mean value of the vector
mean_value = np.mean(random_vector)

print("Random vector:", random_vector)
print("Mean value:", mean_value)


Random vector: [ 0.17920982  1.56654198 -0.60785542  0.91890593  0.73372901  0.67597262
 -0.10974645 -0.29902192 -0.39340294  0.37029869 -1.55691324 -2.41816342
 -1.01335934  1.93084235 -0.2422475   1.20548746 -1.17058189 -0.84608993
 -1.00089622  2.20165116 -0.59091297  0.66508778 -0.51817141  0.64147732
 -0.24855537 -0.18714512 -0.11922466 -0.49636818  1.01048743 -0.219361  ]
Mean value: 0.0020558185635322895


In [21]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
import numpy as np

# Define the shape of the 2D array
rows, cols = 6, 6  

# Create a 2D array filled with zeros
array_2d = np.zeros((rows, cols))

# Set the border elements to 1
array_2d[0, :] = 1
array_2d[:, 0] = 1
array_2d[-1, :] = 1
array_2d[:, -1] = 1

print(array_2d)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
import numpy as np

# Example existing array
existing_array = np.ones((3, 3))  # Replace this with your existing array

# Determine the shape of the new larger array
rows, cols = existing_array.shape[0] + 2, existing_array.shape[1] + 2

# Create a new larger array filled with zeros
new_array = np.zeros((rows, cols))

# Place the existing array inside the new array, leaving a border of zeros
new_array[1:-1, 1:-1] = existing_array

print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(new_array)


Existing Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with Border:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#### 17. What is the result of the following expression? (★☆☆)
#```python
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
#0.3 == 3 * 0.1
import numpy as np

result_1 = 0 * np.nan  
result_2 = np.nan == np.nan  
result_3 = np.inf > np.nan  
result_4 = np.nan - np.nan  
result_5 = np.nan in set([np.nan])  
result_6 = 0.3 == 3 * 0.1  

print("Result 1:", result_1)
print("Result 2:", result_2)
print("Result 3:", result_3)
print("Result 4:", result_4)
print("Result 5:", result_5)
print("Result 6:", result_6)


Result 1: nan
Result 2: False
Result 3: False
Result 4: nan
Result 5: True
Result 6: False


In [24]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix_5x5 = np.zeros((5, 5))

# Assign values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix_5x5[1:], [1, 2, 3, 4])

print(matrix_5x5)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [25]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
import numpy as np
matrix_8x8 = np.zeros((8, 8), dtype=int)
matrix_8x8[1::2, ::2] = 1  
matrix_8x8[::2, 1::2] = 1  
print(matrix_8x8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
import numpy as np

# Define the shape of the array
array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)

index_100th_element = 99  # (Since indexing starts from 0)
# Finding the index (x, y, z) of the 100th element
index_xyz = np.unravel_index(index_100th_element, array_shape)

print("Index (x, y, z) of the 100th element:", index_xyz)


Index (x, y, z) of the 100th element: (1, 5, 3)


In [27]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
import numpy as np
checkerboard_tile = np.array([[0, 1], [1, 0]])
checkerboard_8x8 = np.tile(checkerboard_tile, (4, 4))
print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.randn(5, 5)
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)
normalized_matrix = (random_matrix - mean_value) / std_deviation
print("Original random matrix:")
print(random_matrix)
print("\nNormalized matrix:")
print(normalized_matrix)


Original random matrix:
[[ 0.32854522  1.38700689  1.26124114 -0.83518978 -0.60353496]
 [-1.15666809  0.30549532 -0.23804843  0.12578436 -1.20845235]
 [-0.96920533 -1.61213294  0.72591475 -0.58166454  1.0833478 ]
 [-0.21224302 -1.04453192  0.53600758 -1.62183058  0.91894018]
 [ 1.74672559  0.99069094 -1.39271184  0.37730543  0.34740379]]

Normalized matrix:
[[ 0.38778766  1.46167482  1.33407623 -0.79290704 -0.5578762 ]
 [-1.11907041  0.36440185 -0.18706325  0.18207186 -1.17160935]
 [-0.92887567 -1.58117298  0.79094826 -0.53568705  1.15359036]
 [-0.16088176 -1.00530003  0.59827347 -1.59101195  0.98678674]
 [ 1.82663589  1.05958316 -1.35855415  0.43725848  0.40692106]]


In [29]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
import numpy as np

# Create a custom dtype for RGBA colors using np.dtype()
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example color in RGBA format
example_color = np.array((255, 127, 64, 255), dtype=rgba_dtype)

print("Custom RGBA dtype:")
print(rgba_dtype)
print("\nExample RGBA color:")
print(example_color)


Custom RGBA dtype:
[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]

Example RGBA color:
(255, 127, 64, 255)


In [30]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
import numpy as np
# Create a 5x3 matrix
matrix_5x3 = np.random.rand(5, 3)
# Create a 3x2 matrix
matrix_3x2 = np.random.rand(3, 2)

# Perform matrix multiplication
result_matrix = np.dot(matrix_5x3, matrix_3x2)

print("5x3 Matrix:")
print(matrix_5x3)
print("\n3x2 Matrix:")
print(matrix_3x2)
print("\nResult of multiplication (5x3) dot (3x2):")
print(result_matrix)


5x3 Matrix:
[[0.81076481 0.04119796 0.23902625]
 [0.27081264 0.99536305 0.48520638]
 [0.93608472 0.38925484 0.87495954]
 [0.81624837 0.39578054 0.27816205]
 [0.39314868 0.85625383 0.43789154]]

3x2 Matrix:
[[0.85350372 0.07637263]
 [0.12307822 0.51511874]
 [0.15570095 0.90695634]]

Result of multiplication (5x3) dot (3x2):
[[0.73427796 0.29992845]
 [0.42919421 0.97347383]
 [0.98309261 1.06555381]
 [0.78869308 0.51849383]
 [0.50912019 0.86824669]]


In [31]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 4, 6, 7, 9, 2, 5, 3, 8])

# Negate elements between 3 and 8
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1

print("Original 1D array:")
print(array_1d)


Original 1D array:
[ 1 -4 -6 -7  9  2 -5  3  8]


In [33]:
#### 26. What is the output of the following script? (★☆☆)
#```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [34]:
#### 27. How to round away from zero a float array ? (★☆☆)
import numpy as np

# Example float array
float_array = np.array([-2.6, -1.5, 0.0, 1.3, 2.8])

# Round away from zero
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print("Original float array:")
print(float_array)
print("\nRounded away from zero:")
print(rounded_array)


Original float array:
[-2.6 -1.5  0.   1.3  2.8]

Rounded away from zero:
[-3. -2.  0.  2.  3.]


In [35]:
#### 28. How to find common values between two arrays? (★☆☆)
import numpy as np

# Two example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("\nCommon values:", common_values)


Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]

Common values: [3 4 5]


In [37]:
#### 29. How to get the dates of yesterday, today and tomorrow? (★☆☆)
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate dates for yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-01-03
Today: 2024-01-04
Tomorrow: 2024-01-05


In [38]:
#### 30. How to get all the dates corresponding to the month of July 2016? (★★☆)
from datetime import datetime, timedelta

# Define the start and end dates for July 2016
start_date = datetime(2016, 7, 1)
end_date = datetime(2016, 8, 1)
dates_in_july_2016 = [start_date + timedelta(days=x) for x in range((end_date - start_date).days)]
print("Dates corresponding to the month of July 2016:")
for date in dates_in_july_2016:
    print(date.date())


Dates corresponding to the month of July 2016:
2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31
